version: 0.2

phases:
#   install:
#     commands:
#       - yum update -y
#       - yum install -y software-properties-common
#       - add-apt-repository ppa:openjdk-r/ppa
#       - yum update -y
#       - yum install -y openjdk-8-jdk
#       - yum install -y maven
  pre_build:
    commands:
#       - echo Logging in to Amazon ECR...
#       - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
